import * as global from './global';
import * as sn_auth from './sn_auth';
import * as sn_cc from './sn_cc';
import * as sn_clotho from './sn_clotho';
import * as sn_cmdb from './sn_cmdb';
import * as sn_cmdbgroup from './sn_cmdbgroup';
import * as sn_connect from './sn_connect';
import * as sn_discovery from './sn_discovery';
import * as sn_fd from './sn_fd';
import * as sn_hw from './sn_hw';
import * as sn_impex from './sn_impex';
import * as sn_interaction from './sn_interaction';
import * as sn_nlp_sentiment from './sn_nlp_sentiment';
import * as sn_notification from './sn_notification';
import * as sn_notify from './sn_notify';
import * as sn_sc from './sn_sc';
import * as sn_uc from './sn_uc';
import * as sn_ws from './sn_ws';
import { GlideSystem } from './GlideSystem';
declare var gs: GlideSystem;
export { gs };
export { CertificateEncryption } from './CertificateEncryption';
export { GlideAggregate } from './GlideAggregate';
export { GlideDate } from './GlideDate';
export { GlideDateTime } from './GlideDateTime';
export { GlideDBFunctionBuilder } from './GlideDBFunctionBuilder';
export { GlideDigest } from './GlideDigest';
export { GlideDuration } from './GlideDuration';
export { GlideElement } from './GlideElement';
export { GlideElementDescriptor } from './GlideElementDescriptor';
export { GlideEmailOutbound } from './GlideEmailOutbound';
export { GlideFilter } from './GlideFilter';
export { GlideFormScratchpad } from './GlideFormScratchpad';
export { GlideImportLog } from './GlideImportLog';
export { GlideImportSetRun } from './GlideImportSetRun';
export { GlideImportSetTransformer } from './GlideImportSetTransformer';
export { GlideLocale } from './GlideLocale';
export { GlidePluginManager } from './GlidePluginManager';
export { GlideQueryCondition } from './GlideQueryCondition';
export { GlideRecord } from './GlideRecord';
export { GlideSchedule } from './GlideSchedule';
export { GlideScopedEvaluator } from './GlideScopedEvaluator';
export { GlideScriptableInputStream } from './GlideScriptableInputStream';
export { GlideScriptedExtensionPoint } from './GlideScriptedExtensionPoint';
export { GlideAction } from './GlideAction';
export { GlideScriptedProcessor } from './GlideScriptedProcessor';
export { GlideSecureRandomUtil } from './GlideSecureRandomUtil';
export { GlideSecurityUtils } from './GlideSecurityUtils';
export { GlideServletRequest } from './GlideServletRequest';
export { GlideServletResponse } from './GlideServletResponse';
export { GlideSession } from './GlideSession';
export { GlideSPScriptable } from './GlideSPScriptable';
export { GlideStringUtil } from './GlideStringUtil';
export { GlideSysAttachment } from './GlideSysAttachment';
export { GlideSysListControl } from './GlideSysListControl';
export { GlideSystem } from './GlideSystem';
export { GlideTableHierarchy } from './GlideTableHierarchy';
export { GlideTextReader } from './GlideTextReader';
export { GlideTime } from './GlideTime';
export { GlideUICompatibility } from './GlideUICompatibility';
export { GlideURI } from './GlideURI';
export { GlideUser } from './GlideUser';
export { GlideXMLUtil } from './GlideXMLUtil';
export { JSON } from './JSON';
export { PAScorecard } from './PAScorecard';
export { PASnapshot } from './PASnapshot';
export { RenderProperties } from './RenderProperties';
export { SPScriptedFacet } from './SPScriptedFacet';
export { SPScriptedFacetService } from './SPScriptedFacetService';
export { TemplatePrinter } from './TemplatePrinter';
export { Workflow } from './Workflow';
export { XMLDocument2 } from './XMLDocument2';
export { XMLNode } from './XMLNode';
export { XMLNodeIterator } from './XMLNodeIterator';
export { sn_auth };
export { sn_cc };
export { sn_clotho };
export { sn_cmdb };
export { sn_cmdbgroup };
export { sn_connect };
export { sn_discovery };
export { sn_fd };
export { sn_hw };
export { sn_impex };
export { sn_interaction };
export { sn_nlp_sentiment };
export { sn_notification };
export { sn_notify };
export { sn_sc };
export { sn_uc };
export { sn_ws };

// Manually updated scopes
export { global };
